In [3]:
import numpy as np

In [24]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
mat[2][2]

9

In [31]:
np.shape(mat)

(3, 3)

In [35]:
mylist=[1,2,3]
type(mylist)

list

In [38]:
mylist=np.array(mylist)
type(mylist)

numpy.ndarray

In [39]:
np.shape(mylist)

(3,)

In [41]:
arr1=np.random.randint(1,10,10)
arr1

array([9, 3, 2, 6, 5, 7, 2, 2, 4, 5])

In [43]:
arr2=np.random.randint(11,20,10)
arr2

array([13, 18, 12, 18, 13, 18, 19, 12, 16, 19])

In [44]:
arr=arr1+arr2
arr

array([22, 21, 14, 24, 18, 25, 21, 14, 20, 24])

In [45]:
arr=arr1-arr2
arr

array([ -4, -15, -10, -12,  -8, -11, -17, -10, -12, -14])

In [46]:
arr=arr1*arr2
arr

array([117,  54,  24, 108,  65, 126,  38,  24,  64,  95])

In [48]:
arr=arr1+100
arr

array([109, 103, 102, 106, 105, 107, 102, 102, 104, 105])

In [53]:
arr=np.exp(arr1)
arr

array([8.10308393e+03, 2.00855369e+01, 7.38905610e+00, 4.03428793e+02,
       1.48413159e+02, 1.09663316e+03, 7.38905610e+00, 7.38905610e+00,
       5.45981500e+01, 1.48413159e+02])

In [55]:
arr=np.log(arr1)
arr

array([2.19722458, 1.09861229, 0.69314718, 1.79175947, 1.60943791,
       1.94591015, 0.69314718, 0.69314718, 1.38629436, 1.60943791])

In [50]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
b=np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Divide byzZero

In [56]:
a=1
b=0
c=a/b
print(c)

ZeroDivisionError: division by zero

In [60]:
a=np.array([2,1,2,1,2])
b=np.array([0,1,2,3,4])
c=a/b
c

<ipython-input-60-958b0a0c3788>:3: RuntimeWarning: divide by zero encountered in true_divide
  c=a/b


array([       inf, 1.        , 1.        , 0.33333333, 0.5       ])

In [61]:
d=1/b

<ipython-input-61-a02f60c7e75c>:1: RuntimeWarning: divide by zero encountered in true_divide
  d=1/b


In [ ]:
mat=np.array

In [2]:
arrn = np.arange(0,11,2).reshape(2,3)
arrn

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [3]:
type(arrn)

numpy.ndarray

In [11]:
arrn = np.arange(0,100,2).reshape(5,5)
arrn

ValueError: cannot reshape array of size 50 into shape (5,5)

In [12]:
arrn=np.arange(0,100).reshape(10,10)
arrn

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
mat=np.random.randint(0,110,5)
mat


array([ 3, 87,  6, 93, 96])

In [7]:
nmat=np.arange(1,51).reshape(5,10)
nmat

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [10]:
nmat[1:4,2:8]
# here rows start from 1st row(11,12,13,14.....) till 3rd row(31,32,33,34,......) 4th not included
# similarly columns start from 2nd column(3,13,23,...) till 7th row (7,17,27,...)8th not included

array([[13, 14, 15, 16, 17, 18],
       [23, 24, 25, 26, 27, 28],
       [33, 34, 35, 36, 37, 38]])

In [11]:
nmat[2][3]

24

In [18]:
arr=nmat[:1,:]
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [16]:
arr.max()

10

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arr=np.linspace(0,10,12)
arr
# divide the intervel between 0 and 10(10 icluded) into 12 intervels

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])