# Pandas

In [1]:
import pandas as pd

In [4]:
l=[5,6,7,8,9,3]
print(l)
print(type(l))

[5, 6, 7, 8, 9, 3]
<class 'list'>


In [5]:
s=pd.Series(l)
print(s)
print(type(s))

0    5
1    6
2    7
3    8
4    9
5    3
dtype: int64
<class 'pandas.core.series.Series'>


In [2]:
s1=pd.Series([2,3,5,6.7,8.9,3.4,'3','w','y'])
s1
type(s1)

pandas.core.series.Series

In [7]:
s1=pd.Series([2,3,5,6.7,8.9,3.4,'3','w','y'])
s1.values

array([2, 3, 5, 6.7, 8.9, 3.4, '3', 'w', 'y'], dtype=object)

In [5]:
s2=pd.Series([5,5,6,7,6,6,6,8,7])
print(s2.unique())
s2.index

[5 6 7 8]


RangeIndex(start=0, stop=9, step=1)

In [10]:
s3=pd.Series([1,2,3,4], index=['a','b','c','d'])
s3

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
v=[5,6,7,8,9]
i=[100,200,300,400,500]
s4=pd.Series(v,i)
s4
s4=pd.Series(i,v)
s4


5    100
6    200
7    300
8    400
9    500
dtype: int64

In [12]:
s4=pd.Series(index=i,data=v)
s4

100    5
200    6
300    7
400    8
500    9
dtype: int64

In [3]:
import numpy as np

n=np.random.random(5)
print(n)
n1=np.random.randint(0,10,5)
n1
s=pd.Series(n,n1)
s

[0.22600636 0.06207912 0.4380108  0.21842313 0.64435676]


7    0.226006
9    0.062079
9    0.438011
8    0.218423
2    0.644357
dtype: float64

In [16]:
d={'monkey':153 ,'rat':212 ,'cotton':334 ,'fan':98}
print("Dictionary is: ", d)

s=pd.Series(d)
s

Dictionary is:  {'monkey': 153, 'rat': 212, 'cotton': 334, 'fan': 98}


monkey    153
rat       212
cotton    334
fan        98
dtype: int64

In [18]:
s4[100]
s4[0]#0 index is absent

KeyError: 0

In [19]:
s4[0:4]

100    5
200    6
300    7
400    8
dtype: int64

In [20]:
s4.mean()

7.0

In [23]:
s4[0:6]

100    5
200    6
300    7
400    8
500    9
dtype: int64

In [26]:
dir(s4)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__r

In [27]:
s4.median()

7.0

In [31]:
print(s4)
s4.max()

100    5
200    6
300    7
400    8
500    9
dtype: int64


9

In [29]:
s4.min()

5

In [38]:
s5=pd.Series([1,2,3,4],[100,200,300,400])
s5

100    1
200    2
300    3
400    4
dtype: int64

In [39]:
s4.add(s5)
# NaN not an element

100     6.0
200     8.0
300    10.0
400    12.0
500     NaN
dtype: float64

In [40]:
s5.subtract(s4)

100   -4.0
200   -4.0
300   -4.0
400   -4.0
500    NaN
dtype: float64

In [41]:
s4.subtract(s5)

100    4.0
200    4.0
300    4.0
400    4.0
500    NaN
dtype: float64

In [50]:
# Task 1: Make a dictionary to add name and marks of s students
n=int(input("Entere no of students: "))
students={}
for i in range(n):
    name=(input("enter name of student: "))
    mark=(input("enter mark of student: "))
    students[name]=mark


Entere no of students: 3
enter name of student: a
enter mark of student: 2
enter name of student: b
enter mark of student: 2
enter name of student: c
enter mark of student: 8


In [52]:
s=pd.Series(students)
s

a    2
b    2
c    8
dtype: object

In [57]:
s.min()
print("Name of student with minimum marks: ",s.min())

KeyError: '2'

In [54]:
s.max()

'8'

In [58]:
d1={'a':1,'b':2,'c':3}
s1=pd.Series(d1)
print(s1)

d2={'e':5,'f':6,'g':7}
s2=pd.Series(d2)
print(s2)


a    1
b    2
c    3
dtype: int64
e    5
f    6
g    7
dtype: int64


In [59]:
df = pd.DataFrame({'column 1':s1,'column':s2})
print(df)
print(type(df))

   column 1  column
a       1.0     NaN
b       2.0     NaN
c       3.0     NaN
e       NaN     5.0
f       NaN     6.0
g       NaN     7.0
<class 'pandas.core.frame.DataFrame'>


In [60]:
d3={'a':5,'b':6,"c":7}
s3=pd.Series(d3)
print(s3)

a    5
b    6
c    7
dtype: int64


In [61]:
df = pd.DataFrame({'col 1':s1, 'col 2':s3})
print(df)
print(type(df))

   col 1  col 2
a      1      5
b      2      6
c      3      7
<class 'pandas.core.frame.DataFrame'>


In [5]:
population_d = {'California': 3833, 'Texas': 8193,
                'New York': 6511, 'Florida': 5560, 'Ohio': 1135}  

population_d


{'California': 3833,
 'Texas': 8193,
 'New York': 6511,
 'Florida': 5560,
 'Ohio': 1135}

In [6]:
area_d = {'California': 423967, 'Texas': 695662, 'New York': 141297,   
             'Florida': 170312}

area_d


{'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312}

In [7]:
states=pd.DataFrame({'Population':population_d,"Area":area_d})
states

Population      Area
California        3833  423967.0
Texas             8193  695662.0
New York          6511  141297.0
Florida           5560  170312.0
Ohio              1135       NaN

In [67]:
# to check summary of dataframe
states.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, California to Ohio
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Population  5 non-null      int64
 1   Area        5 non-null      int64
dtypes: int64(2)
memory usage: 120.0+ bytes


In [68]:
# to print any specific column
states.Area

California    423967
Texas         695662
New York      141297
Florida       170312
Ohio          149995
Name: Area, dtype: int64

In [69]:
states['Area']

California    423967
Texas         695662
New York      141297
Florida       170312
Ohio          149995
Name: Area, dtype: int64

In [70]:
## Dataframes using arrays

In [72]:
n=np.random.randint(0,10,(6,4))
n

array([[2, 6, 1, 7],
       [2, 6, 1, 4],
       [3, 0, 7, 4],
       [4, 5, 6, 2],
       [1, 6, 9, 1],
       [6, 2, 5, 8]])

In [74]:
d=pd.DataFrame(n)
d

0  1  2  3
0  2  6  1  7
1  2  6  1  4
2  3  0  7  4
3  4  5  6  2
4  1  6  9  1
5  6  2  5  8

In [77]:
col=['A','B','C','D']
d=pd.DataFrame(n,columns=col)
d

A  B  C  D
0  2  6  1  7
1  2  6  1  4
2  3  0  7  4
3  4  5  6  2
4  1  6  9  1
5  6  2  5  8

In [94]:
rows=['i','ii','iii','iv','v','vi']
d=pd.DataFrame(n,columns=col,index=rows)
d

A  B  C  D
i    2  6  1  7
ii   2  6  1  4
iii  3  0  7  4
iv   4  5  6  2
v    1  6  9  1
vi   6  2  5  8

In [96]:
d[['A','D']]

A
i    2
ii   2
iii  3
iv   4
v    1
vi   6

In [97]:
d[['A']]

A
i    2
ii   2
iii  3
iv   4
v    1
vi   6

In [98]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, i to vi
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int32
 1   B       6 non-null      int32
 2   C       6 non-null      int32
 3   D       6 non-null      int32
dtypes: int32(4)
memory usage: 144.0+ bytes


In [99]:
d.shape

(6, 4)

In [100]:
d.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [101]:
d.dtypes

A    int32
B    int32
C    int32
D    int32
dtype: object

In [102]:
data={'Animals': ['cat','cat','turtle','dog','dog','cat','turtle','cat','dog','dog'],
          'Age': [2.5,3,0.5,np.nan,5,2,4.5,np.nan,7,3], 
      'Visits' : [1,3,2,3,2,3,1,1,2,1], 
    'Priority' : ['y','y','n','y','n','n','n','y','n','n']}


labels=['a','b','c','d','e','f','g','h','i','j']
df=pd.DataFrame(data,index=labels)
df


Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [112]:
# print informations about df
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Animals   10 non-null     object 
 1   Age       8 non-null      float64
 2   Visits    10 non-null     int64  
 3   Priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [109]:
# print names of columns
df.columns

Index(['Animals', 'Age', 'Visits', 'Priority'], dtype='object')

In [107]:
# print datatyes of columnns
df.dtypes

Animals      object
Age         float64
Visits        int64
Priority     object
dtype: object

In [108]:
# print indexes
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [110]:
# print only values
df.values

array([['cat', 2.5, 1, 'y'],
       ['cat', 3.0, 3, 'y'],
       ['turtle', 0.5, 2, 'n'],
       ['dog', nan, 3, 'y'],
       ['dog', 5.0, 2, 'n'],
       ['cat', 2.0, 3, 'n'],
       ['turtle', 4.5, 1, 'n'],
       ['cat', nan, 1, 'y'],
       ['dog', 7.0, 2, 'n'],
       ['dog', 3.0, 1, 'n']], dtype=object)

In [111]:
# print unique enties of Animals column
df.Animals.unique()

array(['cat', 'turtle', 'dog'], dtype=object)

In [115]:
# check top 5 entries of DF (by default show 5 entries)
df.head()

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n

In [116]:
df.head(7)

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n

In [117]:
# show last 5 entries
df.tail()

Animals  Age  Visits Priority
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [119]:
# show random 5 entries
# have to give number in sample function always
df.sample(5)

Animals  Age  Visits Priority
d     dog  NaN       3        y
h     cat  NaN       1        y
c  turtle  0.5       2        n
b     cat  3.0       3        y
f     cat  2.0       3        n